version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: renexus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  project-service:
    build:
      context: ./backend/project-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/renexus
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      - postgres

  task-service:
    build:
      context: ./backend/task-service
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/renexus
      NODE_ENV: development
    ports:
      - "3002:3002"
    depends_on:
      - postgres

volumes:
  postgres_data:
