/**
 * Types for the Workflow Automation service
 */

/**
 * Represents a task suggestion generated by the workflow automation service
 */
export interface TaskSuggestion {
  /**
   * Unique identifier for the suggestion
   */
  id: string;
  
  /**
   * Type of suggestion
   */
  type: 'ASSIGNMENT' | 'PRIORITIZATION' | 'STATUS_CHANGE' | 'WORKLOAD_BALANCING';
  
  /**
   * ID of the task this suggestion relates to
   */
  taskId: string;
  
  /**
   * Human-readable suggestion text
   */
  suggestion: string;
  
  /**
   * Reason for the suggestion
   */
  reason: string;
  
  /**
   * Additional data required to apply the suggestion
   */
  data: {
    /**
     * For ASSIGNMENT suggestions: ID of the team member to assign
     */
    assigneeId?: string;
    
    /**
     * For PRIORITIZATION suggestions: new priority level
     */
    priority?: 'LOW' | 'MEDIUM' | 'HIGH' | 'URGENT';
    
    /**
     * For STATUS_CHANGE suggestions: new status
     */
    status?: 'TODO' | 'IN_PROGRESS' | 'REVIEW' | 'COMPLETED';
    
    /**
     * For WORKLOAD_BALANCING suggestions: list of task reassignments
     */
    reassignments?: Array<{
      taskId: string;
      fromUserId: string;
      toUserId: string;
    }>;
  };
}

/**
 * Response format for workflow suggestions API
 */
export interface WorkflowSuggestionsResponse {
  /**
   * List of task suggestions
   */
  suggestions: TaskSuggestion[];
  
  /**
   * Timestamp when suggestions were generated
   */
  generatedAt: string;
  
  /**
   * Project ID these suggestions relate to
   */
  projectId: string;
}

/**
 * Request format for applying a suggestion
 */
export interface ApplySuggestionRequest {
  /**
   * Whether to accept the suggestion (true) or dismiss it (false)
   */
  accept: boolean;
}

/**
 * Response format for applying a suggestion
 */
export interface ApplySuggestionResponse {
  /**
   * Whether the operation was successful
   */
  success: boolean;
  
  /**
   * Optional message with additional information
   */
  message?: string;
  
  /**
   * ID of the suggestion that was applied
   */
  suggestionId: string;
}
