# Prometheus configuration for Renexus
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'renexus_api'
    metrics_path: '/api/metrics'
    static_configs:
    - targets: ['api:3000']

  - job_name: 'renexus_client'
    metrics_path: '/metrics'
    static_configs:
    - targets: ['client:80']

  - job_name: 'node_exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'postgres_exporter'
    static_configs:
    - targets: ['postgres-exporter:9187']

  - job_name: 'redis_exporter'
    static_configs:
    - targets: ['redis-exporter:9121']
